Add `random_state` to HyperparameterOptimization class
zillow/luminaire pull request #125
Opened 2023-01-23 15:28 UTC by papaemman

### Add a `random_state` argument to the *HyperparameterOptimization* class to ensure the reproducibility of results.

Currently, the library doesn't support a **random seed** setup; thus, consecutively, runs can have significant differences without any change in the source code and input data. 

This does not help debug complex pipelines.

Following the **best practices** for python libraries development, I added functionality for the user to define a random seed in the *HyperparameterOptimization* class.

#### Steps

1/ I created a new `utils/` folder and a `validation.py` file with a **check_random_state()** function

2/ I introduced a `random_state` argument in the *HyperparameterOptimization* class and used the **check_random_state()** function to fix the random seed in every call of any **numpy random** function.

For example,

```{python}
# Before
trial_prob = np.random.uniform(0, 1, 1)

# After
rnd = check_random_state(self.random_state)
trial_prob = rnd.uniform(0, 1, 1)
```

3/ For other packages that introduce randomness (`pykalman`, `hyperopt`), I passed the **`random_state`** argument directly in their calls.

```{python}
# pykalman library
kf = KalmanFilter(random_state=self.random_state)

# hyperopt library
hyper_param = fmin(objective, space=space, algo=algo, max_evals=max_evals, show_progressbar=True, rstate=np.random.default_rng(self.random_state))
```

4/ Finally, I added a **new test** (`luminaire/tests/test_hyper.py`) to check the newly added functionality.

### Local env testing

In my local development environment, all tests are passing successfully.

Also, after running multiple iterations, I checked that the Hyperparameter Optimization returns the same results after each iteration if the `random_state` has been specified.

<img width="350" alt="Screenshot 2023-01-23 at 1 18 10 PM" src="https://user-images.githubusercontent.com/34572881/214078426-831ecb88-48ba-49d0-a566-d88e3d25fabf.png">

Please review my solution and let me know if something needs to be improved.

Thank you.

 ### 📥 [Panos Papaemmanouil](https://www.linkedin.com/in/panagiotis-papaemmanouil/)

2023-01-23 15:30 UTC, papaemman commented
Hey @sayanchk, @shahsmit14, @snazzyfox

I opened this PR to add a `random_state` argument to the *HyperparameterOptimization* class to ensure the reproducibility of results.

I'm kindly asking you to review and approve it.

Thank you very much.
Panos

2023-01-30 19:35 UTC, sayanchk approved these changes
@papaemman This is great! Thanks for picking this up. I know getting different set of hyperparameters makes things difficult to debug and interpret. 

The changes look good to me. Thanks for confirming local testing and updating the unit tests.

@shahsmit14 @snazzyfox Please have a look and merge if okay.

2023-01-30 19:38 UTC, sayanchk commented
@papaemman Just as a side note, we might need similar logic to the WindowDensityModel since we are running some bootstrap resampling. It's worth checking that code that can introduce variations due to such randomness. I will create a separate issue and tag you to it since you are already into it.

2023-03-14 23:55 UTC, shahsmit14 commented on luminaire/utils/validation.py
> +    Parameters
You would need to follow the `param`, `return` and `rtype` standard for function comment | [example](https://github.com/zillow/luminaire/blob/master/luminaire/optimization/hyperparameter_optimization.py#L55-L59)

2023-03-14 23:55 UTC, shahsmit14 commented on luminaire/utils/validation.py
> +import numpy as np
Any other file name suggestion for this? Since, we do not want just one file with all utility functions. 
Might be one file per utility type.

2023-03-14 23:55 UTC, shahsmit14 commented on luminaire/optimization/hyperparameter_optimization.py
> +from ..utils import check_random_state
All imports should be declared before `warnings`, you can move this to the first line.

2023-03-14 23:55 UTC, shahsmit14 commented on luminaire/optimization/hyperparameter_optimization.py
> +from ..utils import check_random_state
All imports should follow `from luminaire.utils.xx import yy`

2023-03-14 23:55 UTC, shahsmit14 commented on luminaire/optimization/hyperparameter_optimization.py
> +                 random_state=None,
parameter definition missing

2023-03-14 23:55 UTC, shahsmit14 commented on luminaire/utils/validation.py
> +    if seed is None or seed is np.random:
It would be good to put this whole thing in a try/except block. Also, raising an error and failing the code is the right way here?

2023-03-14 23:57 UTC, shahsmit14 requested changes
Take a look at the code feedback and once they look good we can later approve and merge this.

2024-01-31 19:07 UTC, shahsmit14 commented
Closing this MR as all the feedback for changes are incorporated in https://github.com/zillow/luminaire/pull/131 by using this MR as the base. Thank you @papaemman for authoring this MR.

2024-01-31 19:07 UTC, closed without merging